### ISSUE TITLE
Add new slot button

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/jquery-fsortable#3]
## Need

``` gherkin
As a potential user
When I check out the demo
I want to be impressed.
```
## Deliverables
- [ ] Extend the fsortable layout with a button.
## Solution

Implement a button that will increase the capacity of the fsortable by creating a new empty slot at the end.
## TODO
- [ ] add a plus button at the end of the fsortables.
- [ ] style the button.
- [ ] pressing the button should create a new empty slot at the end of the fsortable,
- [ ] and refresh the fsortable.
