### ISSUE TITLE
Display current capacity

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/jquery-fsortable#4]
## Need

``` gherkin
As a potential user
When I check out the demo
I want to be impressed.
```
## Deliverables
- [x] Display the current  capacity of an fsortable.
## Solution

Add a pseudo-element that will display the current capacity of an fsortable and update it whenever a change occurs. Use the `attr()` method to display the content.
#### Prerequisites
- https://developer.mozilla.org/en-US/docs/Web/CSS/attr
## TODO
- [x] add an `:after` element to the `.fs` class
- [x] style it
- [x] set its content to be `attr(data-content) " slots left"`
- [x] when creating the fsortable instances, set `data-content` to be the number of `.fsortable-empty` elements
- [x] update the attribute on `sortupdate`

**Comment by NiGhTTraX** [comment]
Closed via https://github.com/NiGhTTraX/jquery-fsortable/commit/2864805ca6cca2a38b0b519b000847397a78bcea.
