### ISSUE TITLE
Remove slot numbers

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/jquery-fsortable#5]
## Need

``` gherkin
As a potential user
When I check out the demo
I don't want to be confused.
```
## Deliverables
- [x] The slots have a thin outline and no numbers.
## Solution

Remove the numbers.
#### TODO
- [x] remove the `bg` elements in from `index.html` [here](https://github.com/NiGhTTraX/jquery-fsortable/blob/gh-pages/index.html#L47-L53) and [here](https://github.com/NiGhTTraX/jquery-fsortable/blob/gh-pages/index.html#L66-L70)
- [x] remove the `bg` style rules from [demo.css](https://github.com/NiGhTTraX/jquery-fsortable/blob/gh-pages/stylesheets/demo.css#L13-L29)

**Comment by NiGhTTraX** [comment]
Closed via https://github.com/NiGhTTraX/jquery-fsortable/commit/29db33f388c4aad4431491a6f98242101c86d97f.
